Get conflict sctipts to work.

diff --git a/tsrc-test b/tsrc-test
--- a/tsrc-test
+++ b/tsrc-test
@@ -19,6 +19,11 @@ function reset_pull_request_six() {
   ./tsrc-test-conflict git-push pullRequest6 pullRequest6
 }
 
+function deconflict_pull_request_six() {
+  # Deconflict feature branch with `git --forc push` for pull request 6.
+  ./tsrc-test-conflict git-push pullRequest6ConflictResolved pullRequest6
+}
+
 function create_pull_request() {
   echo ""
   echo "Creating pull requests..."
@@ -61,48 +66,53 @@ function run_tests() {
         "duplicateVote"
         "manyVoters"
         "semiAutoManyVoters"
-        "conflictResolution"
+        "conflict"
+        "conflictResolved"
     )
 
     for test in "${tests[@]}"; do
         full_test_path="testing/integration/privaterepo/${test}.js"
 
-        OUTPUT=$(docker-compose exec -T turbosrc-service npm test "$full_test_path" 2>&1) || {
-            echo "Error running $test test";
-            echo "Output: $OUTPUT";
-            exit 1;
-        }
-        echo "$OUTPUT"
-        sleep 1
-        echo ""
+        if [[ "$test" != "conflict" && "$test" != "conflictResolved" ]]; then
+          OUTPUT=$(docker-compose exec -T turbosrc-service npm test "$full_test_path" 2>&1) || {
+              echo "Error running $test test";
+              echo "Output: $OUTPUT";
+              exit 1;
+          }
+          echo "$OUTPUT"
+          sleep 1
+          echo ""
+        fi
 
         # New code to prompt the user to continue for specific tests
         if [[ "$VISUAL_TESTS" = true && ( "$full_test_path" = "testing/integration/privaterepo/createRepo.js" ) ]]; then
-            echo "Finished $test test. Press 'y' and enter to continue go thru login process"
-            read -n 1 -r key_login
-            if [[ $key_login = "y" ]]; then
-                login_viatui
-                view_image "viatui/chromium-nix-screenshots/login.png"
-                echo "Check if login successful. Run, if necesssary"
-                echo ""
-                echo "docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/login_confirm XXXXX"
-                echo ""
-                echo "Press 'y' and enter when complete."
-                read -n 1 -r key_load_buttons
-                if [[ $key_load_buttons = "y" ]]; then
-                    load_buttons_viatui
-                fi
-                load_buttons_viatui
-                view_image "viatui/chromium-nix-screenshots/load-vote-buttons.png"
+            #echo "Finished $test test. Press 'y' and enter to continue go thru login process"
+            #read -n 1 -r key_login
+            #if [[ $key_login = "y" ]]; then
+            login_viatui
+            view_image "viatui/chromium-nix-screenshots/login.png"
+            sleep 3
+            #    echo "Check if login successful. Run, if necesssary"
+            #    echo ""
+            #    echo "docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/login_confirm XXXXX"
+            #    echo ""
+            #    echo "Press 'y' and enter when complete."
+            #    read -n 1 -r key_load_buttons
+            #    if [[ $key_load_buttons = "y" ]]; then
+            #        load_buttons_viatui
+            #    fi
+            load_buttons_viatui
+            view_image "viatui/chromium-nix-screenshots/load-vote-buttons.png"
 
-            else
-                echo "Test skipped by user."
-                continue
-            fi
+            #else
+            #    echo "Test skipped by user."
+            #    continue
+            #fi
         fi
 
+        # Run tests unless specified to ignore, such as conflict and conflict resolved which are purely viatui tests
         if [[ "$VISUAL_TESTS" = true ]]; then
-            if [[ "$full_test_path" != "testing/integration/privaterepo/createRepo.js" && "$full_test_path" != "testing/integration/privaterepo/createUser.js" && "$full_test_path" != "testing/integration/privaterepo/semiAutoManyVoters.js" ]]; then
+            if [[ "$full_test_path" != "testing/integration/privaterepo/createRepo.js" && "$full_test_path" != "testing/integration/privaterepo/createUser.js" && "$full_test_path" != "testing/integration/privaterepo/semiAutoManyVoters.js" && "$full_test_path" != "testing/integration/privaterepo/conflict.js" && "$full_test_path" != "testing/integration/privaterepo/conflictResolve.js" ]]; then
                 echo "Taking a screenshot of $test test..."
                 docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/container_screenshot.py "${test}".png
                 echo ""
@@ -113,7 +123,7 @@ function run_tests() {
         fi
 
         if [[ "$VISUAL_TESTS" = true && ( "$full_test_path" = "testing/integration/privaterepo/semiAutoManyVoters.js" ) ]]; then
-            docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/vote_merge_pull_request_5.py "${test}".png
+            docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/vote_merge_pull_request_5.py
             sleep 3
             echo "Taking a screenshot of $test test..."
             docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/container_screenshot.py "${test}".png
@@ -121,6 +131,29 @@ function run_tests() {
             echo "Screen shot completed."
             sleep 5
             view_image "viatui/chromium-nix-screenshots/${test}.png"
+        fi
+        if [[ "$VISUAL_TESTS" = true && ( "$full_test_path" = "testing/integration/privaterepo/conflict.js" ) ]]; then
+          # Fail case, shouldn't vote in pull request 6 as in conflict.
+          docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/conflict.py
+          sleep 3
+          echo "Taking a screenshot of $test test..."
+          docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/container_screenshot.py "${test}".png
+          echo ""
+          echo "Screen shot completed."
+          sleep 5
+          view_image "viatui/chromium-nix-screenshots/${test}.png"
+        fi
+        if [[ "$VISUAL_TESTS" = true && ( "$full_test_path" = "testing/integration/privaterepo/conflictResolved.js" ) ]]; then
+          deconflict_pull_request_six
+          # Fail case, shouldn't vote in pull request 6 as in conflict.
+          docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/conflict_resolved.py
+          sleep 3
+          echo "Taking a screenshot of $test test..."
+          docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/container_screenshot.py "${test}".png
+          echo ""
+          echo "Screen shot completed."
+          sleep 5
+          view_image "viatui/chromium-nix-screenshots/${test}.png"
         fi
 
           #  # Ensure pull request 6 is not in conflict
@@ -134,6 +167,33 @@ function run_tests() {
           #  view_image "viatui/chromium-nix-screenshots/${test}.png"
           #  echo "Finished $test test. Press 'y' and enter to continue go thru login process"
     done
+}
+
+function deconflict_visual_test() {
+    # Fail case, shouldn't vote in pull request 6 as in conflict.
+    docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/vote_merge_pull_request_6.py
+    sleep 3
+    echo "Taking a screenshot of $test test..."
+    docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/container_screenshot.py "vote_merge_pull_request_6".png
+    echo ""
+    echo "Screen shot completed."
+    sleep 5
+    view_image "viatui/chromium-nix-screenshots/vote_merge_pull_request_6.png"
+
+    echo "deconflict feature branch with `git --forc push` for pull request 6."
+    deconflict_pull_request_six
+    sleep 5
+
+    # Success case, should vote in pull request 6 is not in conflict.
+    docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/vote_merge_pull_request_6_out_of_conflict.py
+    sleep 3
+    echo "Taking a screenshot of $test test..."
+    docker-compose exec -it viatui /root/.local/bin/poetry run python scripts/container_screenshot.py "vote_merge_pull_request_6_out_of_conflict.png"
+    echo ""
+    echo "Screen shot completed."
+    sleep 5
+    view_image "viatui/chromium-nix-screenshots/vote_merge_pull_request_6_out_of_conflict.png"
+    sleep 5
 }
 
 function view_image() {
