Dev:captures the output of the test commands and prints the output if a test fails.

diff --git a/tsrc-test b/tsrc-test
--- a/tsrc-test
+++ b/tsrc-test
@@ -1,15 +1,15 @@
 #!/bin/bash
 
-set -e
+set -eo pipefail
 
 function delete_fork() {
   REPO=$1
-  docker-compose run  gihtubmakertools -d -r $REPO
+  docker-compose run gihtubmakertools -d -r $REPO
 }
 
 function fork_repo() {
   REPO=$1
-  docker-compose run  fork-repo node fork-repo.js "turbo-src/$REPO"
+  docker-compose run fork-repo node fork-repo.js "turbo-src/$REPO"
 }
 
 function create_pull_request() {
@@ -19,35 +19,25 @@ function create_pull_request() {
   USERNAME=$1
   REPO=$2
 
-  if ! docker-compose run create_pull_requests python create_pull_requests.py "$USERNAME" "$REPO" "master" "pullRequest1" "refactor(lsp): remove redundant client cleanup" "auto pull request"; then
-    echo "Error: pullRequest1 failed."
-    exit 1
-  fi
+  PR_COMMANDS=(
+    "refactor(lsp): remove redundant client cleanup pullRequest1"
+    "refactor(uncrustify): set maximum number of consecutive newlines pullRequest2"
+    "ci(mingw): only enable -municode for MinGW pullRequest3"
+    "docs: add missing termdebug docs from Vim runtime updates pullRequest4"
+    "refactor: missing parenthesis may cause unexpected problems pullRequest5"
+    "refactor(normal): convert function comments to doxygen format pullRequest6"
+  )
 
-  if ! docker-compose run create_pull_requests python create_pull_requests.py "$USERNAME" "$REPO" "master" "pullRequest2" "refactor(uncrustify): set maximum number of consecutive newlines" "auto pull request"; then
-    echo "Error: pullRequest2 failed."
-    exit 1
-  fi
+  for PR in "${PR_COMMANDS[@]}"; do
+    IFS=" " read -r -a PR_ARRAY <<< "$PR"
+    MESSAGE="${PR_ARRAY[0]}"
+    BRANCH_NAME="${PR_ARRAY[1]}"
 
-  if ! docker-compose run create_pull_requests python create_pull_requests.py "$USERNAME" "$REPO" "master" "pullRequest3" "ci(mingw): only enable -municode for MinGW" "auto pull request"; then
-    echo "Error: pullRequest3 failed."
-    exit 1
-  fi
-
-  if ! docker-compose run create_pull_requests python create_pull_requests.py "$USERNAME" "$REPO" "master" "pullRequest4" "docs: add missing termdebug docs from Vim runtime updates" "auto pull request"; then
-    echo "Error: pullRequest4 failed."
-    exit 1
-  fi
-
-  if ! docker-compose run create_pull_requests python create_pull_requests.py "$USERNAME" "$REPO" "master" "pullRequest5" "refactor: missing parenthesis may cause unexpected problems" "auto pull request"; then
-    echo "Error: pullRequest5 failed."
-    exit 1
-  fi
-
-  if ! docker-compose run create_pull_requests python create_pull_requests.py "$USERNAME" "$REPO" "master" "pullRequest6" "refactor(normal): convert function comments to doxygen format" "auto pull request"; then
-    echo "Error: pullRequest6 failed."
-    exit 1
-  fi
+    if ! docker-compose run create_pull_requests python create_pull_requests.py "$USERNAME" "$REPO" "master" "$BRANCH_NAME" "$MESSAGE" "auto pull request"; then
+      echo "Error: $BRANCH_NAME failed."
+      exit 1
+    fi
+  done
 }
 
 function run_tests() {
@@ -67,12 +57,12 @@ function run_tests() {
     )
 
     for test in "${tests[@]}"; do
-        OUTPUT=$(docker-compose exec -T turbosrc-service npm test "$test")
+        OUTPUT=$(docker-compose exec -T turbosrc-service npm test "$test" 2>&1) || {
+            echo "Error running $test test";
+            echo "Output: $OUTPUT";
+            exit 1;
+        }
         echo "$OUTPUT"
-        if [ $? -ne 0 ]; then
-            echo "Error running $test test"
-            exit 1
-        fi
         sleep 5
     done
 }
@@ -118,3 +108,4 @@ case "$3" in
     exit 1
     ;;
 esac
+
